config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications
  # post 'registered_applications_controller/create'

  # get 'registered_applications_controller/show'

  # get 'registered_applications_controller/update'

  # delete 'registered_applications_controller/destroy'

  # get 'registered_applications_controller/new'

  # get 'registered_applications_controller/index'

  namespace :api, defaults: {format: :json} do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end


  devise_for :users
  get 'welcome/index'

  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # namespace :api, defaults: { format: :json } do
  #             # #2
  #   resources :events, only: [:create]
  # end
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user, optional: true
  has_many :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :application
end

app/models/user.rb
class User < ApplicationRecord
  has_many :applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

    skip_before_action :verify_authenticity_token
    before_action :set_access_control_headers
    
    def set_access_control_headers
        # #1
        headers['Access-Control-Allow-Origin'] = '*'
        # #2
        headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
        # #3
        headers['Access-Control-Allow-Headers'] = 'Content-Type'
    end

    def create
        
        @registered_application = Application.find_by(URL: request.env['HTTP_ORIGIN'])

        if @registered_application == nil
            render json: "Unregistered application", status: :unprocessable_entity and return #Needed to add "and return" in order to pass this line of code, otherwise received a doublerender error
        end

        
        @event = Event.new(event_params) 
        @event.application = @registered_application
        
        
        

        if @event.save
            render json: @event, status: :created
            
        else
            render json: {errors: @event.errors}, status: :unprocessable_entity
            
        end
    end


    def preflight
        head 200
    end

    private
    def event_params
        params.require(:event).permit(:event_name)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class API::EventsController < ApplicationController
            # #3
    skip_before_action :verify_authenticity_token, raise: false

    def create
        registered_application = Application.find_by(URL: request.env['HTTP_ORIGIN'])
            
        if registered_application == nil
            render json: "Unregistered application", status: :unprocessable_entity
        end
    end




    private
    def event_params
        params.require(:event).permit(:name)
    end

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def index
    @application = Application.all
  end

  def new
    @application = Application.new 
  end

  def create
    @application = Application.new 
    @application.name = params[:application][:name]
    @application.URL = params[:application][:URL]
    @application.user_id = current_user.id
    
    Application.all.each do |name|
      if name == @application.name
        flash[:notice] = "Application already exists!"
        render :new
      end
    end

    if @application.save
      flash[:notice] = "App was saved!"
      redirect_to root_path
    
    else
      flash.now[:notice] = "There was an error saving your app."
      render :new
    end
  end
  

  def show
    @application = Application.find(params[:id])
    @events = @application.events.group_by(&:event_name)
  end

  def update
  end

  def destroy
    @application = Application.find(params[:id])

    if @application.destroy
      flash[:notice] = "\"#{@application.name}\" was deleted successfully"
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error deleting the app."
      render :show
    end
  end

end

app/controllers/registered_applications_controller_controller.rb
class RegisteredApplicationsControllerController < ApplicationController

  def index
    @application = Application.all
  end

  def new
    @application = Application.new 
  end

  def create
    @application = Application.new 
    @application.name = params[:application][:name]
    @application.URL = params[:application][:URL]
    @application.User_id = current_user.id
    
    Application.all.each do |name|
      if name == @application.name
        flash[:notice] = "Application already exists!"
        render :new
      end
    end

    if @application.save
      flash[:notice] = "App was saved!"
      redirect_to root_path
    
    else
      flash.now[:notice] = "There was an error saving your app."
      render :new
    end
  end
  

  def show
    @application = Application.find(params[:id])
  end

  def update
  end

  def destroy
    @application = Application.find(params[:id])

    if @application.destroy
      flash[:notice] = "\"#{@application.name}\" was deleted successfully"
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error deleting the app."
      render :show
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def form_group_tag(errors, &block)
        css_class = 'form-group'
        css_class << ' has error' if errors.any?

        # #5
        content_tag :div, capture(&block), class: css_class
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_controller_helper.rb
module RegisteredApplicationsControllerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
  </head>

  <body>
    <nav class="navbar">
      <div class="container-fluid set-max-width">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a><%= link_to "BlocMetrics", welcome_index_path, class:"navbar-brand" %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>
          <div class="nav navbar-nav navbar-right left-item">
            
            <% if current_user %>
                <div class="email"><%= current_user.email %> |
                <%= link_to "Sign Out", destroy_user_session_path, class:"btn btn-danger btn-smf", :method => :delete %></div>
            <% else %>
                <%= link_to "Sign Up!", new_user_registration_path, class:"btn btn-primary" %>
                <%= link_to "Sign In!", new_user_session_path, class:"btn btn-success" %>
            <% end %>
            <%# <li><a href="#">Future Link</a></li>
            <li><a href="#">Future Link</a></li>
            <li><a href="#">Future Link</a></li> %>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>



    <%= yield %>







  </body>
</html>

app/views/registered_applications/create.html.erb
<h1>RegisteredApplicationsController#create</h1>
<p>Find me in app/views/registered_applications_controller/create.html.erb</p>

app/views/registered_applications/destroy.html.erb
<h1>RegisteredApplicationsController#destroy</h1>
<p>Find me in app/views/registered_applications/destroy.html.erb</p>

app/views/registered_applications/index.html.erb
<div class="center">
    <h1>Dashboard <%= link_to "New Application", new_registered_application_path, class:"btn btn-success btn-lg" %></h1>
    <h1 class="border marg-top">Your Registered Applications</h1>
    <% current_user.applications.each do |application| %>
        <h2><%= link_to application.name, registered_application_path(application) %><br></h2>
    <% end %>
</div>

app/views/registered_applications/new.html.erb
<h1 class="center">Register New Application</h1>
<div class="row center">
    <div class="center set-content-max-width">
        <%= form_for @application, url: {action: "create"} do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class:"form-control", placeholder: "Enter app name" %>
            </div>
            <div class="form-group">
                <%= f.label :URL %>
                <%= f.text_field :URL, class:"form-control", placeholder: "Enter app URL" %>
            </div>
            <div class="form-group">
            <%= f.submit "Save", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>
</div>

app/views/registered_applications/show.html.erb
<div class="center">
<h1 class="border">Application: <%= @application.name %></h1>
<br>
<h1>Events</h1>
<div class="data center set-max-width">
    <%= pie_chart @application.events.group(:event_name).count, library: {backgroundColor: "#000"} %>
    <%= line_chart @application.events.group_by_day(:created_at).count %><br>
    <%= link_to "Delete App", registered_application_path(@application), class:"btn btn-danger btn-lg", method: :delete %>
</div>
<br>

</div>

app/views/registered_applications/update.html.erb
<h1>RegisteredApplicationsController#update</h1>
<p>Find me in app/views/registered_applications_controller/update.html.erb</p>

app/views/welcome/index.html.erb
<div class="container set-max-width">
    <div class="jumbotron">
        <div class="container">
            <% if current_user %>
                <h1>Welcome to BlocMetrics!</h1>
                <p>Your new favorite analytics app!</p>
                <%= link_to "Dashboard", registered_applications_path, class:"btn btn-success btn-lg" %>
            <% else %>
                <h1>Welcome to BlocMetrics!</h1>
                <p>Your new favorite analytics app!</p>
                <%= link_to "Sign Up!", new_user_registration_path, class:"btn btn-primary btn-lg" %>
                <%= link_to "Sign In!", new_user_session_path, class:"btn btn-success btn-lg" %>
            <% end %>
        </div>
    </div>
</div>